Dev edit profile
chas-academy/u10-business-idea-grupp-6 pull request #83
Opened 2021-05-24 11:07 UTC by stenwall

2021-05-26 08:05 UTC, EnzoBomark requested changes
-21,143 seems sus @ fix: react-modal dependency

2021-05-26 08:41 UTC, EnzoBomark reviewed
👍

2021-05-26 08:41 UTC, EnzoBomark approved these changes

2021-05-27 14:22 UTC, hannesqvarnstrom approved these changes
It looks good and works too! Wow!

2021-05-27 14:23 UTC, merged